version: '3.3'

services:
  build:
    image: jenkins
    ports:
      - "8000:8080"
      - "50000:50000"
    volumes:
      - /mnt/jenkins:/var/jenkins_home
  agent:
    image: madajaju/jenkins-swarm-node-agent
    deploy:
      mode: global
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    secrets:
      - source: jenkins-v1
        target: jenkins
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /mnt/registry:/var/lib/registry
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
        - /mnt/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    command: --host unix:///var/run/docker.sock

secrets:
  jenkins-v1: 
    file: ./jenkins-secret.txt
